doc-warnings: yes

ignore-paths:
  - doc/examples

ignore-patterns:
    - ^example/doc_.*\.py$
    - #!/usr/bin/env python3
    - # -*- coding: utf-8 -*-
    - __init__.py

pylint:
  disable:
    - too-many-local-variables
    - too-many-arguments
