doc-warnings: yes

ignore-paths:
  - docs/
  - mlens/externals
  - dev/

ignore-patterns:
    - ^example/doc_.*\.py$
    - __init__.py

pylint:
  disable:
    - too-many-local-variables
    - too-many-arguments
