language: python

matrix:
    include:
        - python: 3.6
        - python: 3.5
        - python: 2.7

install:
  - set -e
  - sudo apt-get update
  - pip install coverage coveralls
  - pip install nose-exclude
  - pip install flake8
  - pip install -r requirements.txt
  - python setup.py install

script:
  - set -e
  - nosetests -s -v --with-coverage --exclude mlens/visualization --exclude mlens/externals
  - flake8 --exclude externals

after_success:
  - coveralls
