language: python

os:
  - linux
  - osx

matrix:
    include:
        - python: 2.7
        - python: 3.5
        - python: 3.6

install:
  - ./.travis/install.sh

script:
  - set -e
  - nosetests -s -v --with-coverage --exclude mlens/visualization --exclude mlens/externals

after_success:
  - coveralls
