language: python
python:
  - "3.5"
install:
  - pip install coveralls
  - pip install pytest
  - pip install -r requirements.txt
  - pip install .
script:
  - coverage run mlens/tests/test_simple.py
after_success:
  coveralls
