language: python
python:
  - "3.5"
install:
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install .
script:
  - coverage run --source=mlens mlens/test/test.py
  - python mlens/test/test.py
after_success:
  coveralls
