language: python

matrix:
    include:
        - python: 3.5
        - python: 3.6
        - python: 2.7

install:
  - set -e
  - sudo apt-get update
  - pip install coverage coveralls
  - pip install nose nose-exclude
  - pip install flake8
  - pip install -r requirements.txt
  - pip install .

script:
  - set -e
  - nosetests -s -v --with-coverage --exclude mlens/visualization --exclude mlens/externals --exclude mlens/dev
  - flake8 --exclude [mlens/visualization, mlens/externals, dev]

after_success:
  - coveralls
