language: python

matrix:
    include:
        - os: linux
          python: 3.6
        - os: linux
          python: 3.5
        - os: linux
          python: 2.7
        - os: osx
          language: generic
          python: 3.6
        - os: osx
          language: generic
          python: 3.5
        - os: osx
          language: generic
          python: 2.7

install:
  - set -e
  - mlens_dev/.travis/install.sh

script:
  - set -e
  - nosetests -s -v --with-coverage --exclude mlens/visualization --exclude mlens/externals

after_success:
  - coveralls
