language: python

os:
  - linux
  - osx

matrix:
    include:
        - python: 3.5
        - python: 3.6
        - python: 2.7

install:
  - set -e
  - sudo apt-get update
  - pip install coverage coveralls
  - pip install nose nose-exclude 
  - pip install -r requirements.txt
  - pip install .

script:
  - set -e
  - nosetests -s -v --with-coverage --exclude */visualization --exclude */externals --exclude */dev
  - flake8 --exclude [*/visualization, */externals, */dev]

after_success:
  coveralls
