language: python

matrix:
    include:
        - os: linux
          python: 3.6
          sudo: required
        - os: linux
          python: 3.5
          sudo: required
        - os: linux
          python: 2.7
          sudo: required
        - os: osx
          language: generic
          sudo: required
          python: 3.6
        - os: osx
          language: generic
          sudo: required
          python: 3.5
        - os: osx
          language: generic
          sudo: required
          python: 2.7

install:
  - set -e
  - .travis/install.sh
  - python --version

script:
  - set -e
  - nosetests -s -v --with-coverage --exclude mlens/visualization --exclude mlens/externals

after_success:
  - coveralls
