package:
  name: mlens
  version: "0.1.0"

source:
  git_rev: v0.1.0
  git_url: https://github.com/flennerhag/mlens.git

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.11
    - scipy >=0.17

  run:
    - python
    - numpy >=1.11
    - scipy >=0.17

test:
  requires:
    - nose-exclude

  imports:
    - mlens
    - mlens.base
    - mlens.ensemble
    - mlens.externals
    - mlens.metrics
    - mlens.model_selection
    - mlens.parallel
    - mlens.preprocessing
    - mlens.utils


about:
  home: https://github.com/flennerhag/mlens
  license: MIT
  license_file: LICENSE
